flask_blog/flask_app/models/__init__.py
from .entity_model import Entry
from .tag_model import Tag

flask_blog/flask_app/models/entity_model.py
import datetime
from ..app import db
from ..utils import slugify

from .relationship_tables import entry_tags


class Entry(db.Model):
    __tablename__ = 'entry'

    STATUS_PUBLIC = 0
    STATUS_DRAFT = 1
    STATUS_DELETED = 2

    TYPE_MICRO = 0
    TYPE_MAJOR = 1

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    slug = db.Column(db.String(100), nullable=False, unique=True)
    body = db.Column(db.Text)
    status = db.Column(db.SmallInteger, default=STATUS_DRAFT)
    type = db.Column(db.SmallInteger, default=TYPE_MICRO)

    created_timestamp = db.Column(
        db.DateTime,
        default=datetime.datetime.now)  # , index=True)

    modified_timestamp = db.Column(
        db.DateTime,
        default=datetime.datetime.now,
        onupdate=datetime.datetime.now)

    # querying 'TAG'
    # via entry_tags
    # allowing to go from TAG to associated entries
    # instead of it loading all the associated entries, we want a Query object
    tags = db.relationship(
        'Tag',
        secondary=entry_tags,
        backref=db.backref('entries', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Entry, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        self.slug = ''
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return f'<Entry: {self.title}>'

flask_blog/flask_app/models/relationship_tables.py
from ..app import db

entry_tags = db.Table('entry_tags',
                      db.Column(
                          'tag_id',
                          db.Integer,
                          db.ForeignKey('tag.id')),

                      db.Column(
                          'entry_id',
                          db.Integer,
                          db.ForeignKey('entry.id'))
                      )

flask_blog/flask_app/models/tag_model.py
from ..app import db
from ..utils import slugify

# from .relationship_tables import entry_tags


class Tag(db.Model):
    __tablename__ = 'tag'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    slug = db.Column(db.String(64), nullable=False, unique=True)

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Tag {self.name}>'

flask_blog/flask_app/controllers/entries/forms.py
import wtforms
from wtforms.validators import DataRequired
from collections import namedtuple

from ...services import EntryService, TagService


class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            return '; '.join([tag.name for tag in self.data])
        return ''

    def get_tags_from_string(self, tag_string):
        raw = tag_string.split(';')
        tag_names = [name.strip() for name in raw if name.strip()]
        tags = TagService.create_tags_from_name_list(tag_names)
        return [*tags]

    def process_formdata(self, valuelist):
        if valuelist:

            self.old_tags, self.new_tags = self.get_tags_from_string(
                valuelist[0])
            self.data = self.old_tags + self.new_tags
        else:
            self.old_tags, self.new_tags = []
            self.data = []

    def get_new_tags(self):
        return self.new_tags


class EntryForm(wtforms.Form):
    title = wtforms.StringField('Название', validators=[DataRequired()])
    body = wtforms.TextAreaField('Контент', validators=[DataRequired()])
    tags = TagField('Тэги', description="Теги разделяются точкой с запятой")
    status = wtforms.SelectField(
        'Статус',
        choices=(
            (EntryService.VALID_STATUSES[0], 'Черновое'),
            (EntryService.VALID_STATUSES[1], 'Обобществлённое')
        ),
        coerce=int)

    type = wtforms.SelectField(
        'Тип',
        choices=(
            (EntryService.VALID_TYPES[0],  'Твит'),
            (EntryService.VALID_TYPES[1],  'Пост')
        ),
        coerce=int)

    def save_entry(self):
        entry = EntryService.get_new_entry()
        entry = self.modify_entry(entry)
        return entry

    def modify_entry(self, entry):
        self.populate_obj(entry)
        entry = EntryService.save_entry(entry)
        return entry

    def save_new_tags(self):
        new_tags = self.tags.get_new_tags()
        TagService.save_tag_list(new_tags)
        return new_tags

flask_blog/flask_app/__init__.py
from .app import app, manager
from .main import *

flask_blog/flask_app/app.py
from flask import Flask
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy


from .config import DebugConfig

############
# App
############
app = Flask(__name__)

app.config.from_object(DebugConfig)  # ToDo
db = SQLAlchemy(app)
migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

flask_blog/flask_app/config/__init__.py
from .config import Configuration as DebugConfig

flask_blog/flask_app/controllers/__init__.py
from .entries import *

flask_blog/flask_app/controllers/entries/__init__.py
from .blueprint import entries

flask_blog/flask_app/controllers/entries/blueprint.py
from flask import Blueprint, flash, render_template, redirect, url_for, request
from collections import namedtuple

from .forms import EntryForm
from ...helpers import markdown, get_anchors, parse_anchors_as_bootstrap
from ...helpers import render_paginated

from ...services.entry import EntryService, TagService

from ...app import db

DummyTag = namedtuple("DummyTag", ["name"])


entries = Blueprint(
    'entries',
    __name__,
    template_folder='templates')


@entries.route('/')
def index():
    entries = EntryService.get_entries_ordered_by_date()
    return render_paginated('entries/index.html', entries)


@entries.route('/tags/')
def tag_index():
    tags = TagService.get_tag_list_ordered_by_name()
    return render_paginated('entries/index_tag.html', tags)


def single_tag_search(slug):
    tag = TagService.get_tag_by_slug(slug)
    entries = EntryService.get_entries_by_tag(tag)
    return render_paginated('entries/detail_tag.html', entries, tag=tag)


def multiple_tag_search(slug_list):
    ''' 
    '''
    tags = TagService.get_tags_by_slug_multiple(slug_list)
    if tags is None:
        entries = None
        tags = [DummyTag(name=slug) for slug in slug_list]
    else:
        entries = EntryService.get_entries_by_tags(tags)

    return render_paginated('entries/detail_tag.html',
                            entries,
                            tag=tags)


@entries.route('/tags/<slug>/')
def tag_detail(slug):
    if '+' in slug:
        slug_list = slug.split('+')
    else:
        slug_list = [slug]
    # if len(slug_list) == 1:
        # return multiple_tag_search(slug)
    # else:
    return multiple_tag_search(slug_list)


# Creation model
def create_entry_post():
    form = EntryForm(request.form)
    if form.validate():
        result = form.save_entry()
        flash(f'Статья «{result.title}» создана', 'success')
        return redirect(url_for('entries.detail', slug=result.slug))
    else:
        return render_template('entries/create.html', form=form)


@entries.route('/create/', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        return create_entry_post()
    elif request.method == 'GET':
        form = EntryForm()
        return render_template('entries/create.html', form=form)
    else:
        assert request.method in [
            'GET', 'POST'], "Unexpected behaviour: only get and post requests assumed"


@entries.route('/<slug>/')
def detail(slug):
    entry = EntryService.get_entry_by_slug(slug)
    anchors = get_anchors(entry.body)
    main_data = markdown(
        entry.body, anchors, math=True, fenced_code=True)
    anch = parse_anchors_as_bootstrap(
        anchors)
    return render_template('entries/detail.html', entry=entry, rendered_data=main_data, scrollspy=anch)

# Edit model


def entry_edit_post_responce(slug: str):
    # obj param help to autofill form from entry by comparing attributes
    entry = EntryService.get_entry_by_slug(slug)
    form = EntryForm(request.form, obj=entry)
    if form.validate():
        tags = form.save_new_tags()
        entry = form.modify_entry(entry)
        flash(f'Изменения в статье «{entry.title}» сохранены', 'success')
        return redirect(url_for('entries.detail', slug=entry.slug))
    else:
        return render_template('entries/edit.html', entry=entry, form=form)


def entry_edit_get_responce(slug: str):
    entry = EntryService.get_entry_by_slug(slug)
    form = EntryForm(obj=entry)
    return render_template('entries/edit.html', entry=entry, form=form)


@entries.route('/<slug>/edit', methods=['GET', 'POST'])
def edit(slug):
    if request.method == 'POST':
        return entry_edit_post_responce(slug)
    elif request.method == 'GET':
        return entry_edit_get_responce(slug)
    else:
        assert request.method in [
            'GET', 'POST'], "Unexpected behaviour: only get and post requests assumed"


def entry_delete_post_responce(slug: str):
    entry = EntryService.get_entry_by_slug(slug)
    entry = EntryService.delete_entry(entry)
    flash(f'Статье «{entry.title}» присвоен статус удаленные', 'success')
    return redirect(url_for('entries.index'))


def entry_delete_get_responce(slug: str):
    entry = EntryService.get_entry_by_slug(slug)
    return render_template('entries/delete.html', entry=entry)


@entries.route('/<slug>/delete', methods=['GET', 'POST'])
def delete(slug):
    if request.method == 'POST':
        return entry_delete_post_responce(slug)
    elif request.method == 'GET':
        return entry_delete_get_responce(slug)
    else:
        assert request.method in [
            'GET', 'POST'], "Unexpected behaviour: only get and post requests assumed"

flask_blog/flask_app/controllers/origin.py
from ..app import app
from flask import redirect, request, abort, render_template, url_for


@app.route('/')
def homepage():
    return render_template("index.html")

flask_blog/flask_app/helpers/__init__.py
from .helpers import markdown, get_anchors, parse_anchors_as_bootstrap
from .entry_helpers import render_paginated

flask_blog/flask_app/main.py
from .app import app, db  # import our Flask app
from .models import Tag, Entry

from .controllers import origin
from .controllers.entries import entries

app.register_blueprint(entries, url_prefix='/entries')

if __name__ == '__main__':
    app.run()

flask_blog/flask_app/services/__init__.py
from .entry import EntryService, TagService

flask_blog/flask_app/services/entry/__init__.py
from .entity_service import EntryService
from .tag_service import TagService

flask_blog/flask_app/utils/__init__.py
from .slug_processor import slugify

flask_blog/flask_app/templates/entries/create.html
{% extends 'base.html' %}
{% from 'macros/form_field.html' import form_field  %}
{% from 'macros/form_control.html' import form_control %}


{% block title %}
    Создание новой статьи    
{% endblock title %}

{% block content_title %}
    Создание новой статьи
{% endblock content_title %}

{% block content %}
    <form action="{{ url_for('entries.create') }}"  method="post">
        {% for field in form %}
            {{ form_field(field) }}
        {% endfor %}
        {{ form_control(url_for('entries.index'), submit_name="Создать") }}
    </form>    
{% endblock content %}

flask_blog/flask_app/templates/entries/delete.html
{% extends 'base.html' %}
{% from 'macros/form_control.html' import form_control %}


{% block title %}
    {{ entry.title }}
{% endblock title %}

{% block content_title %}
    {{ entry.title }}
{% endblock content_title %}

{% block content %}
    <form action="{{ url_for('entries.delete', slug=entry.slug) }}" method="post">
        <fieldset>
            <legend>Удалить эту запись?</legend>
            {{ form_control( url_for('entries.detail', slug=entry.slug), submit_name="Удалить") }}
        </fieldset>
    </form>
{% endblock content %}

flask_blog/flask_app/templates/entries/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ entry.title }}
{% endblock title %}

{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/detail.css') }}">
{% endblock %}

{% block extra_scripts %}
    <script src="{{ url_for('static', filename='js/hotfixes.js') }}"></script>
{% endblock %}

{% block content_title %}
    {{ entry.title }} 
{% endblock content_title %}

{% block content_control %}
    <nav class="btn-group" role="group"> 
        <a href="{{ url_for('entries.edit', slug=entry.slug) }}" class="btn btn-secondary">
            <i class="far fa-edit" aria-hidden="true"></i>
        </a>
        <a href="{{ url_for('entries.delete', slug=entry.slug) }}" class="btn btn-secondary" >
            <i class="far fa-trash-alt" aria-hidden="true"></i>
        </a>
    </nav>
{% endblock content_control %}

{% block sidebar %}
    <nav id = "tag-info" class = "container-fluid">
        <h4>Тэги</h4>
        {% for tag in entry.tags | sort(attribute="name") %}
            <a class="badge badge-secondary" 
                href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">
            {{ tag.name }}
            </a> 
        {% endfor %}
        <p>Опубликовано {{ entry.created_timestamp.strftime('%m/%d/%Y')}}</p>
    </nav>
    <div id = "toc-info" class = "container-fluid">
        <h4>Оглавление</h4>
        <nav id = "navbar-scrollspy">
            {{ scrollspy | safe}}
        </nav>
    </div>
{% endblock sidebar %}

{% block content %}
    {{ rendered_data }}
{% endblock content %}

flask_blog/flask_app/templates/entries/detail_tag.html
{% extends 'base.html' %}

{% block title %}
    {% if tag is iterable and (tag is not string and tag is not mapping) %}
        Записи по тегам « 
        {% for elem in tag %} 
            {{ elem.name }} 
        {% endfor %} »
    {% else %}
        Записи по тегу «{{tag.name}}»
    {% endif %}
    
{% endblock title %}

{% block content_title %}
    {% if tag is iterable and (tag is not string and tag is not mapping) %}
        Записи по тегам « 
        {% for elem in tag %} 
            {{ elem.name }} 
        {% endfor %} »
    {% else %}
        Записи по тегу «{{tag.name}}»
    {% endif %}
{% endblock content_title %}

{% block content %}
    {% include 'includes/list.html' %}
    {% include 'includes/page_links.html' %}
{% endblock content %}

flask_blog/flask_app/templates/entries/edit.html
{% extends 'base.html' %}
{% from 'macros/form_field.html' import form_field %}
{% from 'macros/form_control.html' import form_control %}


{% block title %}
    Правка «{{ entry.title }}»    
{% endblock title %}

{% block content_title %}
    Правка «{{ entry.title }}»    
{% endblock content_title %}

{% block content %}
    <form action="{{ url_for('entries.edit', slug=entry.slug) }}" method="post">
        {% for field in form %}
            {{ form_field(field) }}            
        {% endfor %}
        {{ form_control( url_for('entries.detail', slug=entry.slug), submit_name="Сохранить") }}
    </form>
{% endblock content %}

flask_blog/flask_app/templates/entries/index.html
{% extends "base.html" %}  

{% block title %}Entries{% endblock %}

{% block content_title %}Entries{% endblock %}

{% block content %}
    
    {% include "includes/list.html" %}
    {% include 'includes/page_links.html' %}

{% endblock %}

flask_blog/flask_app/templates/entries/index_tag.html
{% extends 'base.html' %}

{% block title %}
    Теги
{% endblock title %}

{% block content_title %}
    Список тегов
{% endblock content_title %}

{% block content %}
    <ul>
    {% for tag in object_list.items %}
        <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a></li>
    {% endfor %}
    </ul>
    
    {% include 'includes/page_links.html' %}
{% endblock content %}